# -*- coding: utf-8 -*-
import webbrowser
import sys
import os

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QUrl, QPropertyAnimation, QEasingCurve
from PyQt5.QtGui import QDesktopServices, QColor, QLinearGradient, QPalette
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QVBoxLayout, QGraphicsDropShadowEffect
from PyQt5.QtGui import QFont, QPixmap, QBrush
from PyQt5.QtCore import Qt


def get_resource_path(relative_path):
    """获取资源文件的正确路径，兼容开发和打包环境"""
    try:
        # 打包后的环境：资源在临时目录
        base_path = sys._MEIPASS
    except Exception:
        # 开发环境：资源与当前文件同目录
        base_path = os.path.abspath(os.path.dirname(__file__))
    return os.path.join(base_path, relative_path)



class BruceLeeButton(QtWidgets.QPushButton):
    def __init__(self, text, parent=None):
        super().__init__(text, parent)
        self.setStyleSheet("""
            BruceLeeButton {
                background-color: #00a1cb;
                color: #ffffff;  /* 纯白色文字提高按钮文字对比度 */
                border: 2px solid #0066cc;
                border-radius: 8px;
                font-family: 'Microsoft YaHei UI';
                font-weight: bold;
                padding: 5px 10px;
            }
            BruceLeeButton:hover {
                background-color: #008fb3;
                border: 2px solid #004d80;
            }
            BruceLeeButton:pressed {
                background-color: #0066cc;
                color: #ffffff;
            }
        """)
        shadow = QGraphicsDropShadowEffect()
        shadow.setBlurRadius(10)
        shadow.setColor(QColor(0, 0, 0, 150))
        shadow.setOffset(3, 3)
        self.setGraphicsEffect(shadow)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 840)
        # 使用资源路径函数设置图标
        icon_path = get_resource_path("wu.ico")
        MainWindow.setWindowIcon(QtGui.QIcon(icon_path))

        # 设置主窗口背景为深色，提高文字对比度
        palette = MainWindow.palette()
        gradient = QLinearGradient(0, 0, 0, 840)
        # 使用深蓝色渐变背景，为文本提供良好衬托
        gradient.setColorAt(0, QColor("#1a2436"))
        gradient.setColorAt(1, QColor("#0f1724"))
        palette.setBrush(QPalette.Window, QBrush(gradient))
        MainWindow.setPalette(palette)

        # 添加李小龙主题背景
        self.background_label = QtWidgets.QLabel(MainWindow)
        self.background_label.setGeometry(0, 0, 800, 840)

        # 关键修改：使用资源路径函数获取图片路径并使用QPixmap加载
        bg_image_path = get_resource_path("bruce_bg.jpg")

        # 检查文件是否存在
        if os.path.exists(bg_image_path):
            pixmap = QtGui.QPixmap(bg_image_path)
            if not pixmap.isNull():
                # 缩放图片以适应窗口
                scaled_pixmap = pixmap.scaled(
                    800, 840,
                    QtCore.Qt.KeepAspectRatioByExpanding,
                    QtCore.Qt.SmoothTransformation
                )
                self.background_label.setPixmap(scaled_pixmap)
                self.background_label.setAlignment(QtCore.Qt.AlignCenter)

                # 设置透明度
                opacity_effect = QtWidgets.QGraphicsOpacityEffect()
                opacity_effect.setOpacity(0.88)
                self.background_label.setGraphicsEffect(opacity_effect)
            else:
                print(f"无法加载背景图片: {bg_image_path}")
        else:
            print(f"背景图片不存在: {bg_image_path}")
            # 调试信息
            print(f"当前工作目录: {os.getcwd()}")
            print(f"尝试列出临时目录: {os.listdir(os.path.dirname(bg_image_path))}")

        # 中心部件容器
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setGeometry(0, 100, 800, 750)
        self.centralwidget.setStyleSheet("background-color: transparent;")

        # 串口设置区域
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 740, 90))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("""
            QGroupBox {
                background-color: rgba(30, 40, 60, 80);  /* 半透明深蓝背景 */
                border: 2px solid #00a1cb;
                border-radius: 10px;
                color: #ffffff;  /* 亮蓝色标题文字 */
                font-size: 14px;
                padding-top: 15px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top center;
                padding: 0 10px;
            }
        """)
        self.groupBox.setObjectName("groupBox")

        # 串口按钮保持不变
        self.pushButton_7 = BruceLeeButton("Serial Setup", self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 35, 100, 40))

        self.pushButton_8 = BruceLeeButton("Open", self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 35, 100, 40))

        self.pushButton_9 = BruceLeeButton("Close", self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 35, 100, 40))

        # 状态标签使用亮青色提高醒目度
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(460, 35, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: #80e0ff;")  # 亮青色文字
        self.label_16.setText("Status:")

        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(530, 35, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: #a0ffd0; font-size: 16px;")  # 亮红色状态文字
        self.label_17.setText("Standby")

        # 状态LED指示灯
        self.status_led = QtWidgets.QLabel(self.groupBox)
        self.status_led.setGeometry(QtCore.QRect(680, 35, 30, 30))
        self.status_led.setStyleSheet("background-color: #ff6b6b; border-radius: 15px; border: 1px solid #00a1cb;")

        # 命令发送区域
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(390, 120, 380, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("""
            QGroupBox {
                background-color: rgba(30, 40, 60, 80);
                border: 2px solid #00a1cb;
                border-radius: 10px;
                color: #ffffff;
                font-size: 14px;
                padding-top: 15px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top center;
                padding: 0 10px;
            }
            QTextBrowser {
                background-color: rgba(15, 23, 36, 90);  /* 深色背景 */
                color: #a0ffd0;  
                border: 1px solid #00a1cb;
                border-radius: 5px;
                font-family: 'Consolas';
                font-size: 12px;
            }
            QLineEdit {
                background-color: rgba(15, 23, 36, 90);
                color: #a0ffd0;  /* 亮绿色输入文本 */
                border: 1px solid #00a1cb;
                border-radius: 5px;
                font-size: 12px;
            }
        """)
        self.groupBox_5.setObjectName("groupBox_5")

        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser.setGeometry(QtCore.QRect(20, 40, 340, 220))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.textBrowser.setFont(font)

        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 270, 340, 120))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_8.setStyleSheet("color: #ffffff;")  # 子标题颜色

        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 30, 320, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEdit_14.setFont(font)

        self.pushButton_3 = BruceLeeButton("Send", self.groupBox_8)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 70, 100, 35))

        self.pushButton_4 = BruceLeeButton("Send with CRC", self.groupBox_8)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 70, 120, 35))

        self.pushButton_10 = BruceLeeButton("Clear", self.groupBox_5)
        self.pushButton_10.setGeometry(QtCore.QRect(290, 10, 70, 25))

        # 命令接收区域
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(390, 540, 380, 280))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("""
            QGroupBox {
                background-color: rgba(30, 40, 60, 80);
                border: 2px solid #00a1cb;
                border-radius: 10px;
                color: #ffffff;
                font-size: 14px;
                padding-top: 15px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top center;
                padding: 0 10px;
            }
            QTextBrowser {
                background-color: rgba(15, 23, 36, 90);
                color: #a0ffd0;  
                border: 1px solid #00a1cb;
                border-radius: 5px;
                font-family: 'Consolas';
                font-size: 12px;
            }
        """)
        self.groupBox_6.setObjectName("groupBox_6")

        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_6)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 40, 340, 220))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.textBrowser_2.setFont(font)

        self.pushButton_16 = BruceLeeButton("Clear", self.groupBox_6)
        self.pushButton_16.setGeometry(QtCore.QRect(290, 10, 70, 25))

        # 电机控制面板
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 120, 340, 700))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("""
            QGroupBox {
                background-color: rgba(30, 40, 60, 80);
                border: 2px solid #00a1cb;
                border-radius: 10px;
                color: #ffffff;
                font-size: 14px;
                padding-top: 15px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top center;
                padding: 0 10px;
            }
            QLabel {
                color: #b0e0ff;  /* 亮蓝色标签文字 */
                font-size: 12px;
            }
            QLineEdit {
                background-color: rgba(15, 23, 36, 90);
                color: #a0ffd0;  /* 亮绿色输入框文字 */
                border: 1px solid #00a1cb;
                border-radius: 5px;
                font-size: 12px;
            }
        """)
        self.groupBox_2.setObjectName("groupBox_2")

        # 电机参数
        self.groupBox_90 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_90.setGeometry(QtCore.QRect(10, 30, 320, 130))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.groupBox_90.setFont(font)
        self.groupBox_90.setStyleSheet("""
            QGroupBox {
                background-color: rgba(20, 30, 50, 80);
                border: 1px solid #0066cc;
                border-radius: 8px;
                color: #ffffff;  /* 更亮的标题颜色 */
                font-size: 13px;
            }
        """)
        self.groupBox_90.setObjectName("groupBox_90")

        # 电机参数控件保持布局不变，颜色已通过父容器设置

        self.label_90 = QtWidgets.QLabel(self.groupBox_90)
        self.label_90.setGeometry(QtCore.QRect(10, 30, 40, 23))
        self.label_90.setText("ID:")

        self.lineEdit_90 = QtWidgets.QLineEdit(self.groupBox_90)
        self.lineEdit_90.setGeometry(QtCore.QRect(30, 30, 25, 25))
        self.lineEdit_90.setText("1")

        self.pushButton_90 = BruceLeeButton("✓", self.groupBox_90)
        self.pushButton_90.setGeometry(QtCore.QRect(55, 30, 30, 25))

        self.label_92 = QtWidgets.QLabel(self.groupBox_90)
        self.label_92.setGeometry(QtCore.QRect(105, 30, 50, 23))
        self.label_92.setText("PPR:")

        self.lineEdit_92 = QtWidgets.QLineEdit(self.groupBox_90)
        self.lineEdit_92.setGeometry(QtCore.QRect(135, 30, 50, 25))
        self.lineEdit_92.setText("3200")

        self.pushButton_92 = BruceLeeButton("✓", self.groupBox_90)
        self.pushButton_92.setGeometry(QtCore.QRect(185, 30, 30, 25))

        self.label_93 = QtWidgets.QLabel(self.groupBox_90)
        self.label_93.setGeometry(QtCore.QRect(225, 30, 60, 25))
        self.label_93.setText("CW/CCW")

        self.pushButton_93 = BruceLeeButton("✓", self.groupBox_90)
        self.pushButton_93.setGeometry(QtCore.QRect(280, 30, 30, 25))

        self.label_91 = QtWidgets.QLabel(self.groupBox_90)
        self.label_91.setGeometry(QtCore.QRect(10, 65, 60, 23))
        self.label_91.setText("mA:")

        self.lineEdit_91 = QtWidgets.QLineEdit(self.groupBox_90)
        self.lineEdit_91.setGeometry(QtCore.QRect(35, 65, 50, 25))


        self.pushButton_91 = BruceLeeButton("🔍", self.groupBox_90)
        self.pushButton_91.setGeometry(QtCore.QRect(85, 65, 30, 25))

        self.label_scp_1 = QtWidgets.QLabel(self.groupBox_90)
        self.label_scp_1.setGeometry(QtCore.QRect(135, 65, 100, 23))
        self.label_scp_1.setText("Standby Current:")

        self.lineEdit_scp = QtWidgets.QLineEdit(self.groupBox_90)
        self.lineEdit_scp.setGeometry(QtCore.QRect(238, 65, 30, 25))
        self.lineEdit_scp.setText("30")

        self.label_scp = QtWidgets.QLabel(self.groupBox_90)
        self.label_scp.setGeometry(QtCore.QRect(268, 65, 10, 23))
        self.label_scp.setText("%")

        self.pushButton_scp = BruceLeeButton("✓", self.groupBox_90)
        self.pushButton_scp.setGeometry(QtCore.QRect(280, 65, 30, 25))

        # 新增！！ AR28驱动器 单独添加的设置Peak Current 百分比
        self.label_peakc_1 = QtWidgets.QLabel(self.groupBox_90)
        self.label_peakc_1.setGeometry(QtCore.QRect(10, 100, 225, 23))
        self.label_peakc_1.setText("Set the Percentage of the Peak Current:")

        self.lineEdit_peakc = QtWidgets.QLineEdit(self.groupBox_90)
        self.lineEdit_peakc.setGeometry(QtCore.QRect(238, 100, 30, 25))
        self.lineEdit_peakc.setText("45")

        self.label_scp = QtWidgets.QLabel(self.groupBox_90)
        self.label_scp.setGeometry(QtCore.QRect(268, 100, 10, 23))
        self.label_scp.setText("%")

        self.pushButton_peak_current = BruceLeeButton("✓", self.groupBox_90)
        self.pushButton_peak_current.setGeometry(QtCore.QRect(280, 100, 30, 25))

        # 速度控制
        self.groupBox_91 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_91.setGeometry(QtCore.QRect(10, 170, 320, 310))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.groupBox_91.setFont(font)
        self.groupBox_91.setStyleSheet("""
            QGroupBox {
                background-color: rgba(20, 30, 50, 80);
                border: 1px solid #0066cc;
                border-radius: 8px;
                color: #ffffff;
                font-size: 13px;
            }
        """)
        self.groupBox_91.setObjectName("groupBox_91")

        # 运动控制按钮
        self.pushButton_enable = BruceLeeButton("Enable", self.groupBox_91)
        self.pushButton_enable.setGeometry(QtCore.QRect(10, 30, 70, 35))

        self.pushButton_disable = BruceLeeButton("Disable", self.groupBox_91)
        self.pushButton_disable.setGeometry(QtCore.QRect(90, 30, 70, 35))

        self.pushButton_save = BruceLeeButton("Save", self.groupBox_91)
        self.pushButton_save.setGeometry(QtCore.QRect(170, 30, 60, 35))

        self.pushButton_restore = BruceLeeButton("Restore", self.groupBox_91)
        self.pushButton_restore.setGeometry(QtCore.QRect(240, 30, 70, 35))

        # 速度设置
        self.label_94 = QtWidgets.QLabel(self.groupBox_91)
        self.label_94.setGeometry(QtCore.QRect(10, 75, 300, 25))
        self.label_94.setText("Speed (pulses/s):")

        self.lineEdit_94 = QtWidgets.QLineEdit(self.groupBox_91)
        self.lineEdit_94.setGeometry(QtCore.QRect(10, 105, 100, 30))
        self.lineEdit_94.setText("6000")

        self.pushButton_94 = BruceLeeButton("✓", self.groupBox_91)
        self.pushButton_94.setGeometry(QtCore.QRect(110, 105, 40, 30))

        self.lineEdit_94_q = QtWidgets.QLineEdit(self.groupBox_91)
        self.lineEdit_94_q.setGeometry(QtCore.QRect(170, 105, 100, 30))

        self.pushButton_94_q = BruceLeeButton("🔍", self.groupBox_91)
        self.pushButton_94_q.setGeometry(QtCore.QRect(270, 105, 40, 30))

        # 加速度设置
        self.label_acc = QtWidgets.QLabel(self.groupBox_91)
        self.label_acc.setGeometry(QtCore.QRect(10, 140, 300, 25))
        self.label_acc.setText("Acceleration (pulses/s²):")

        self.lineEdit_acc = QtWidgets.QLineEdit(self.groupBox_91)
        self.lineEdit_acc.setGeometry(QtCore.QRect(10, 170, 100, 30))
        self.lineEdit_acc.setText("10000")

        self.pushButton_acc = BruceLeeButton("✓", self.groupBox_91)
        self.pushButton_acc.setGeometry(QtCore.QRect(110, 170, 40, 30))

        self.lineEdit_acc_q = QtWidgets.QLineEdit(self.groupBox_91)
        self.lineEdit_acc_q.setGeometry(QtCore.QRect(170, 170, 100, 30))

        self.pushButton_acc_q = BruceLeeButton("🔍", self.groupBox_91)
        self.pushButton_acc_q.setGeometry(QtCore.QRect(270, 170, 40, 30))

        # 减速度设置
        self.label_dec = QtWidgets.QLabel(self.groupBox_91)
        self.label_dec.setGeometry(QtCore.QRect(10, 205, 300, 25))
        self.label_dec.setText("Deceleration (pulses/s²):")

        self.lineEdit_dec = QtWidgets.QLineEdit(self.groupBox_91)
        self.lineEdit_dec.setGeometry(QtCore.QRect(10, 235, 100, 30))
        self.lineEdit_dec.setText("10000")

        self.pushButton_dec = BruceLeeButton("✓", self.groupBox_91)
        self.pushButton_dec.setGeometry(QtCore.QRect(110, 235, 40, 30))

        self.lineEdit_dec_q = QtWidgets.QLineEdit(self.groupBox_91)
        self.lineEdit_dec_q.setGeometry(QtCore.QRect(170, 235, 100, 30))

        self.pushButton_dec_q = BruceLeeButton("🔍", self.groupBox_91)
        self.pushButton_dec_q.setGeometry(QtCore.QRect(270, 235, 40, 30))

        # 速度控制按钮
        self.pushButton_94B = BruceLeeButton("◀◀", self.groupBox_91)
        self.pushButton_94B.setGeometry(QtCore.QRect(10, 270, 80, 35))

        self.pushButton_94S = BruceLeeButton("||", self.groupBox_91)
        self.pushButton_94S.setGeometry(QtCore.QRect(120, 270, 80, 35))

        self.pushButton_94F = BruceLeeButton("▶▶", self.groupBox_91)
        self.pushButton_94F.setGeometry(QtCore.QRect(230, 270, 80, 35))

        # 位置控制
        self.groupBox_92 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_92.setGeometry(QtCore.QRect(10, 500, 320, 190))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        self.groupBox_92.setFont(font)
        self.groupBox_92.setStyleSheet("""
            QGroupBox {
                background-color: rgba(20, 30, 50, 80);
                border: 1px solid #0066cc;
                border-radius: 8px;
                color: #ffffff;
                font-size: 13px;
            }
        """)
        self.groupBox_92.setObjectName("groupBox_92")

        # 位置控制按钮
        self.pushButton_set0 = BruceLeeButton("Set Zero", self.groupBox_92)
        self.pushButton_set0.setGeometry(QtCore.QRect(10, 30, 80, 35))

        self.pushButton_incr = BruceLeeButton("Incremental", self.groupBox_92)
        self.pushButton_incr.setGeometry(QtCore.QRect(110, 30, 100, 35))

        self.pushButton_abso = BruceLeeButton("Absolute", self.groupBox_92)
        self.pushButton_abso.setGeometry(QtCore.QRect(230, 30, 80, 35))

        # 位置设置
        self.label_dis = QtWidgets.QLabel(self.groupBox_92)
        self.label_dis.setGeometry(QtCore.QRect(10, 75, 300, 25))
        self.label_dis.setText("Position (pulses):")

        self.lineEdit_95 = QtWidgets.QLineEdit(self.groupBox_92)
        self.lineEdit_95.setGeometry(QtCore.QRect(10, 105, 100, 30))
        self.lineEdit_95.setText("60000")

        self.pushButton_95 = BruceLeeButton("✓", self.groupBox_92)
        self.pushButton_95.setGeometry(QtCore.QRect(110, 105, 40, 30))

        self.lineEdit_dis_q = QtWidgets.QLineEdit(self.groupBox_92)
        self.lineEdit_dis_q.setGeometry(QtCore.QRect(170, 105, 100, 30))

        self.pushButton_dis_q = BruceLeeButton("🔍", self.groupBox_92)
        self.pushButton_dis_q.setGeometry(QtCore.QRect(270, 105, 40, 30))

        # 位置控制按钮
        self.pushButton_95B = BruceLeeButton("◀◀", self.groupBox_92)
        self.pushButton_95B.setGeometry(QtCore.QRect(10, 150, 80, 35))

        self.pushButton_95S = BruceLeeButton("||", self.groupBox_92)
        self.pushButton_95S.setGeometry(QtCore.QRect(120, 150, 80, 35))

        self.pushButton_95F = BruceLeeButton("▶▶", self.groupBox_92)
        self.pushButton_95F.setGeometry(QtCore.QRect(230, 150, 80, 35))

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.setStyleSheet("color: #b0e0ff; background-color: rgba(15, 23, 36, 90);")  # 状态栏颜色
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 添加动画
        self.add_animations()

    def add_animations(self):
        # 状态LED动画
        self.led_animation = QPropertyAnimation(self.status_led, b"geometry")
        self.led_animation.setDuration(1000)
        self.led_animation.setLoopCount(-1)  # 无限循环
        self.led_animation.setStartValue(QtCore.QRect(680, 35, 30, 30))
        self.led_animation.setEndValue(QtCore.QRect(680, 35, 25, 25))
        self.led_animation.setEasingCurve(QEasingCurve.InOutQuad)
        self.led_animation.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AR28 | RS485 Driver Test Software"))
        self.groupBox.setTitle(_translate("MainWindow", "Serial Port Settings"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Command Sending"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Hex Command"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Command Receiving"))
        self.groupBox_90.setTitle(_translate("MainWindow", "Motor Parameters"))
        self.groupBox_91.setTitle(_translate("MainWindow", "Speed Control"))
        self.groupBox_92.setTitle(_translate("MainWindow", "Position Control"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Motor Control Panel"))


# 程序入口
if __name__ == '__main__':
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps)
    app = QtWidgets.QApplication(sys.argv)
    app.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps)

    # 设置全局字体
    font = QFont("Microsoft YaHei UI", 9)
    app.setFont(font)

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())