# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rs.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 300)  # 增加窗口大小
        Form.setMinimumSize(QtCore.QSize(320, 300))
        Form.setMaximumSize(QtCore.QSize(320, 300))

        # 设置主窗口背景颜色
        Form.setStyleSheet("background-color: #f0f2f5;")

        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 280, 230))  # 增加高度
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)  # 增加字体大小
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        # 为组框添加圆角和背景色
        self.groupBox.setStyleSheet("""
            QGroupBox {
                background-color: white;
                border: 1px solid #dcdfe6;
                border-radius: 8px;
                margin-top: 1ex;
                padding-top: 10px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 5px;
            }
        """)

        # 标签样式 - 透明背景和蓝色字体
        label_style = """
                    QLabel {
                        background-color: transparent;
                        color: #1890ff;
                    }
                """
        # 增加标签和组合框之间的间距
        y_offset = 30
        step = 35

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, y_offset, 70, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet(label_style)  # 应用标签样式
        self.label.setObjectName("label")

        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(120, y_offset, 130, 28))  # 增加高度
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        # 添加圆角样式
        self.comboBox.setStyleSheet("""
            QComboBox {
                background-color: white;
                border: 1px solid #1890ff;
                border-radius: 4px;
                padding: 0 8px;
                min-height: 28px;
            }
            QComboBox::drop-down {
                subcontrol-origin: padding;
                subcontrol-position: top right;
                width: 20px;
                border-left: 1px solid #dcdfe6;
            }
        """)

        y_offset += step
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, y_offset, 70, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(label_style)  # 应用标签样式
        self.label_2.setObjectName("label_2")

        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(120, y_offset, 130, 28))  # 增加高度
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.setStyleSheet(self.comboBox.styleSheet())

        y_offset += step
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, y_offset, 70, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(label_style)  # 应用标签样式
        self.label_3.setObjectName("label_3")

        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(120, y_offset, 130, 28))  # 增加高度
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.setStyleSheet(self.comboBox.styleSheet())

        y_offset += step
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, y_offset, 70, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(label_style)  # 应用标签样式
        self.label_4.setObjectName("label_4")

        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(120, y_offset, 130, 28))  # 增加高度
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.setStyleSheet(self.comboBox.styleSheet())

        y_offset += step
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, y_offset, 70, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(label_style)  # 应用标签样式
        self.label_5.setObjectName("label_5")

        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(120, y_offset, 130, 28))  # 增加高度
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.setStyleSheet(self.comboBox.styleSheet())

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(200, 260, 100, 30))  # 增加高度和宽度
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        # 为按钮添加圆角和渐变背景
        self.pushButton.setStyleSheet("""
            QPushButton {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 #4da1ff, stop:1 #1e88e5);
                color: white;
                border: none;
                border-radius: 6px;
                min-height: 30px;
                min-width: 50px;
                font-weight: normal;
            }
            QPushButton:hover {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 #64b5f6, stop:1 #2196f3);
            }
            QPushButton:pressed {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 #1e88e5, stop:1 #1976d2);
            }
        """)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Serial Port Settings"))
        # 恢复组框标题设置，包括冒号
        self.groupBox.setTitle(_translate("Form", "Serial Port Settings："))
        self.label.setText(_translate("Form", "Serial Port:"))
        self.label_2.setText(_translate("Form", "Baud Rate:"))
        self.label_3.setText(_translate("Form", "Parity:"))
        self.label_4.setText(_translate("Form", "Byte Size:"))
        self.label_5.setText(_translate("Form", "Stop Bits:"))
        self.pushButton.setText(_translate("Form", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon("./logo.ico"))
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())